apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        value: le6u1v0
      - name: SECRET_PASSWORD
        value: leonspassword
  restartPolicy: Never


# root@secret-env-pod:/data# env | grep SECRET
# SECRET_USERNAME=le6u1v0
# SECRET_PASSWORD=leonspassword