apiVersion: v1
kind: Secret
metadata:
  name: leonssecret
type: Opaque
stringData:
  USER_NAME: le6u1v0
  PASSWORD: leonspassword


# Type:  Opaque

# Data
# ====
# PASSWORD:   13 bytes
# USER_NAME:  7 bytes