apiVersion: v1
kind: Pod
metadata:
  name: secretref-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: leonssecret
            key: USER_NAME
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: leonssecret
            key: PASSWORD
  restartPolicy: Never


# root@secretref-pod:/data# env |grep SECRET
# SECRET_USERNAME=le6u1v0
# SECRET_PASSWORD=leonspassword

    # Environment:
    #   SECRET_USERNAME:  <set to the key 'USER_NAME' in secret 'leonssecret'>  Optional: false
    #   SECRET_PASSWORD:  <set to the key 'PASSWORD' in secret 'leonssecret'>   Optional: false
