apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: leons-csi-class
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "leons-user-assigned-identity"
    keyvaultName: "leonsakv011"
    objects: |
      array:
        - |
          objectName: username              
          objectType: secret
          objectVersion: ""
        - |
          objectName: password              
          objectType: secret
          objectVersion: ""  
    tenantId: "3617ef9b-98b4-40d9-ba43-e1ed6709cf0d"

# one secretproviderclass per AKV
